target 'HongFu' do
platform :ios, '8.0'
pod 'AFNetworking','~>3.1.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'Masonry','~>1.0'
#pod 'FMDB','~>2.6.2'
#pod 'MBProgressHUD','~>1.0'
pod 'MJRefresh'
pod 'JSONKit'
#pod 'IQKeyboardManager'
#轮播图
pod 'SDCycleScrollView'
#播放音乐
#pod 'StreamingKit'
end
